parser: '@typescript-eslint/parser'

plugins:
  - simple-import-sort

extends:
  - eslint:recommended
  - plugin:@typescript-eslint/eslint-recommended
  - plugin:@typescript-eslint/recommended
  - plugin:import/recommended
  - plugin:import/typescript
  - prettier/@typescript-eslint
  - plugin:prettier/recommended

rules:
  '@typescript-eslint/array-type':
    - error
    - default: array-simple
  '@typescript-eslint/explicit-function-return-type':
    - error
    - allowExpressions: true
      allowTypedFunctionExpressions: true
  '@typescript-eslint/no-use-before-define':
    - error
    - functions: false
  simple-import-sort/sort:
    - error
