parser: '@typescript-eslint/parser'

plugins:
  - '@typescript-eslint'

extends:
  - eslint:recommended
  - plugin:@typescript-eslint/eslint-recommended
  - plugin:@typescript-eslint/recommended
  - plugin:prettier/recommended
  - prettier/@typescript-eslint

rules:
  '@typescript-eslint/array-type':
    - error
    - default: array-simple
  '@typescript-eslint/explicit-function-return-type':
    - error
    - allowExpressions: true
      allowTypedFunctionExpressions: true
  '@typescript-eslint/no-use-before-define':
    - error
    - functions: false
